name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: cd to directory basic_loader
      run: cd basic_loader

    - name: run make_a23
      run: ./make_a23
      
    - name: make_all
      run:  make all

#    - name: Run check
#      run: make check

#    - name: Run distcheck
#      run: make distcheck
