name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: cd to directory basic_loader
      run: cd basic_loader

    - name: Make boot0
      run: make -f make_a23 clean -C boot0; make -f make_a23  -C boot0
      
    - name: Make fes1
      run:  make -f make_a23 clean -C fes1; make -f make_a23  -C fes1

#    - name: Run check
#      run: make check

#    - name: Run distcheck
#      run: make distcheck
